### ISSUE TITLE
Improve Travis build script

### ISSUE THREAD

**Issue by khaeru** [khaeru/py-gdx#10]
`.travis.yml` currently includes:

```yaml
cache:
  directories:
    - $HOME/gams
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION*/lib/python*/site-packages
```

Because the latter directory contains the version of PyGDX that's being tested, the set of files to be cached changes on every build.

- [x] exclude installed pyGDX from cached build files
- [x] add coveralls.io configuration
- [x] switch to using Anaconda for the build environment
